### ISSUE TITLE
Module not found Error

### ISSUE THREAD

**Issue by shijiansu** [yelingfeng/vue-2.0-FamilyBucket#5]
Hi,

When execute npm run dev, it shows error,

ERROR in ./src/store/index.js
Module not found: Error: Can't resolve 'vuex/logger' in '....\yelingfeng-vue2-FamilyBucket\src\store'

Found out it is the path issue for,
import createLogger from 'vuex/logger'

It should be,
import createLogger from 'vuex/dist/logger'

I have made a pull request for this, you can merge it, or you can fix by your side.

Thank you,

**Comment by yelingfeng** [comment]
thks :)

**Comment by shijiansu** [comment]
Thank you ! Nice to meet you~
As the issue is fixed, let us close the issue.
